### ISSUE TITLE
Adding support for matching proccess by exec command and arguments

### ISSUE THREAD

**Issue by hamidrezakp** [hamidrezakp/ChapChap#2]
Currently the app only check if exec command is equal to `command` field.
but we can match by arguments to support some new restricting methods.
for example you need to kill `mpv` when any movie is played. Assuming that movies are in `/home/user/Videos/movies/` folder, so we can use this feature like this:
 ```toml
[[apps]]
name = "APPNAME"
...
command = "mpv"
args = "/home/user/Videos/movies/*"
```
Note: this feature need issue #3 feature.
