### ISSUE TITLE
Support for URL matching mechanism and avoid visiting Websites

### ISSUE THREAD

**Issue by hamidrezakp** [hamidrezakp/ChapChap#4]
Current mechanism is only killing apps but we need to block certain distracting websites like `Youtube` or `Twitter`, we can add this feature using `/etc/hosts` file.

If there is time to block a website, we can insert this line at end of `/etc/hosts/`:
```
127.0.0.1       example.com #chapchap_website="Website_name"
```

and config file can be like this:
```toml
[[urls]]
name = "Youtube"
enabled = true
slices = [ [13:10:00, 12:00:00], [19:00:10, 23:59:00] ] # you can write multiple time slice
black_list = false # time slices are black list or white list?
urls = ["https://*.youtube.com", "https://*.youtu.be"] # Urls to be blocked
```
We can clear all `#chapchap...` lines in `/etc/hosts/` file when starting ChapChap and then insert them by parsing config file and decide if it is time to insert that line.
